version: "3.9"

services:
  postgres:
    image: postgres
    container_name: crm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm_github
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crm_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.docker

volumes:
  pgdata:
